// Target languages: Read Frog's 179 languages, in Read Frog's order.
//
// Source: Read Frog, https://github.com/mengxi-ream/read-frog
// Commit b4a45b9, file src/locales/en.yml (the keys of `languages`).
// Original license: GPL-3.0-only.
// Modified by markdown-twain, 2026-09-28:
// - ISO 639-3 codes are converted to the shortest BCP 47 tag with
//   Intl.getCanonicalLocales; cmn -> zh-Hans and cmn-Hant -> zh-Hant by hand.
// - Names are CLDR names from Intl.DisplayNames (ICU 78.3), generated once and
//   kept only when resolvedOptions() shows the requested locale was used.
//   fuv, zlm, skr, hms and wls have no CLDR English name and use the ISO 639-3
//   reference name; languages without a CLDR native name have no nativeName.
//
// The Target language setting's enum in package.json is generated from this
// table by `pnpm sync:languages`.

export interface Language {
  /** Shortest BCP 47 tag, as stored in the setting. */
  tag: string;
  englishName: string;
  nativeName?: string;
}

export const LANGUAGES: readonly Language[] = [
  { tag: "en", englishName: "English", nativeName: "English" },
  { tag: "zh-Hans", englishName: "Simplified Chinese", nativeName: "简体中文" },
  { tag: "zh-Hant", englishName: "Traditional Chinese", nativeName: "繁體中文" },
  { tag: "yue", englishName: "Cantonese", nativeName: "粵語" },
  { tag: "es", englishName: "Spanish", nativeName: "español" },
  { tag: "ru", englishName: "Russian", nativeName: "русский" },
  { tag: "ar", englishName: "Arabic", nativeName: "العربية" },
  { tag: "bn", englishName: "Bangla", nativeName: "বাংলা" },
  { tag: "hi", englishName: "Hindi", nativeName: "हिन्दी" },
  { tag: "pt", englishName: "Portuguese", nativeName: "português" },
  { tag: "id", englishName: "Indonesian", nativeName: "Indonesia" },
  { tag: "ja", englishName: "Japanese", nativeName: "日本語" },
  { tag: "fr", englishName: "French", nativeName: "français" },
  { tag: "de", englishName: "German", nativeName: "Deutsch" },
  { tag: "jv", englishName: "Javanese", nativeName: "Jawa" },
  { tag: "ko", englishName: "Korean", nativeName: "한국어" },
  { tag: "te", englishName: "Telugu", nativeName: "తెలుగు" },
  { tag: "vi", englishName: "Vietnamese", nativeName: "Tiếng Việt" },
  { tag: "mr", englishName: "Marathi", nativeName: "मराठी" },
  { tag: "it", englishName: "Italian", nativeName: "italiano" },
  { tag: "ta", englishName: "Tamil", nativeName: "தமிழ்" },
  { tag: "tr", englishName: "Turkish", nativeName: "Türkçe" },
  { tag: "ur", englishName: "Urdu", nativeName: "اردو" },
  { tag: "gu", englishName: "Gujarati", nativeName: "ગુજરાતી" },
  { tag: "pl", englishName: "Polish", nativeName: "polski" },
  { tag: "uk", englishName: "Ukrainian", nativeName: "українська" },
  { tag: "kn", englishName: "Kannada", nativeName: "ಕನ್ನಡ" },
  { tag: "mai", englishName: "Maithili", nativeName: "मैथिली" },
  { tag: "ml", englishName: "Malayalam", nativeName: "മലയാളം" },
  { tag: "fa", englishName: "Persian", nativeName: "فارسی" },
  { tag: "my", englishName: "Burmese", nativeName: "မြန်မာ" },
  { tag: "sw", englishName: "Swahili", nativeName: "Kiswahili" },
  { tag: "su", englishName: "Sundanese", nativeName: "Basa Sunda" },
  { tag: "ro", englishName: "Romanian", nativeName: "română" },
  { tag: "pa", englishName: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  { tag: "bho", englishName: "Bhojpuri", nativeName: "भोजपुरी" },
  { tag: "am", englishName: "Amharic", nativeName: "አማርኛ" },
  { tag: "ha", englishName: "Hausa", nativeName: "Hausa" },
  { tag: "fuv", englishName: "Nigerian Fulfulde" },
  { tag: "bs", englishName: "Bosnian", nativeName: "bosanski" },
  { tag: "hr", englishName: "Croatian", nativeName: "hrvatski" },
  { tag: "nl", englishName: "Dutch", nativeName: "Nederlands" },
  { tag: "sr", englishName: "Serbian", nativeName: "српски" },
  { tag: "th", englishName: "Thai", nativeName: "ไทย" },
  { tag: "ckb", englishName: "Central Kurdish", nativeName: "کوردیی ناوەندی" },
  { tag: "yo", englishName: "Yoruba", nativeName: "Èdè Yorùbá" },
  { tag: "uz", englishName: "Uzbek", nativeName: "o‘zbek" },
  { tag: "zlm", englishName: "Malay (individual language)" },
  { tag: "ig", englishName: "Igbo", nativeName: "Igbo" },
  { tag: "ne", englishName: "Nepali", nativeName: "नेपाली" },
  { tag: "ceb", englishName: "Cebuano", nativeName: "Cebuano" },
  { tag: "skr", englishName: "Saraiki" },
  { tag: "fil", englishName: "Filipino", nativeName: "Filipino" },
  { tag: "hu", englishName: "Hungarian", nativeName: "magyar" },
  { tag: "az", englishName: "Azerbaijani", nativeName: "azərbaycan" },
  { tag: "si", englishName: "Sinhala", nativeName: "සිංහල" },
  { tag: "koi", englishName: "Komi-Permyak" },
  { tag: "el", englishName: "Greek", nativeName: "Ελληνικά" },
  { tag: "cs", englishName: "Czech", nativeName: "čeština" },
  { tag: "mag", englishName: "Magahi" },
  { tag: "rn", englishName: "Rundi", nativeName: "Ikirundi" },
  { tag: "be", englishName: "Belarusian", nativeName: "беларуская" },
  { tag: "mg", englishName: "Malagasy", nativeName: "Malagasy" },
  { tag: "qug", englishName: "Chimborazo Highland Quichua" },
  { tag: "mad", englishName: "Madurese" },
  { tag: "ny", englishName: "Nyanja" },
  { tag: "za", englishName: "Zhuang", nativeName: "Vahcuengh" },
  { tag: "ps", englishName: "Pashto", nativeName: "پښتو" },
  { tag: "rw", englishName: "Kinyarwanda", nativeName: "Ikinyarwanda" },
  { tag: "zu", englishName: "Zulu", nativeName: "isiZulu" },
  { tag: "bg", englishName: "Bulgarian", nativeName: "български" },
  { tag: "sv", englishName: "Swedish", nativeName: "svenska" },
  { tag: "ln", englishName: "Lingala", nativeName: "lingála" },
  { tag: "so", englishName: "Somali", nativeName: "Soomaali" },
  { tag: "hms", englishName: "Southern Qiandong Miao" },
  { tag: "hnj", englishName: "Hmong Njua" },
  { tag: "ilo", englishName: "Iloko" },
  { tag: "kk", englishName: "Kazakh", nativeName: "қазақ тілі" },
  { tag: "he", englishName: "Hebrew", nativeName: "עברית" },
  { tag: "nb", englishName: "Norwegian Bokmål", nativeName: "norsk bokmål" },
  { tag: "nn", englishName: "Norwegian Nynorsk", nativeName: "norsk nynorsk" },
  { tag: "af", englishName: "Afrikaans", nativeName: "Afrikaans" },
  { tag: "sq", englishName: "Albanian", nativeName: "shqip" },
  { tag: "as", englishName: "Assamese", nativeName: "অসমীয়া" },
  { tag: "eu", englishName: "Basque", nativeName: "euskara" },
  { tag: "br", englishName: "Breton", nativeName: "brezhoneg" },
  { tag: "ca", englishName: "Catalan", nativeName: "català" },
  { tag: "co", englishName: "Corsican" },
  { tag: "cy", englishName: "Welsh", nativeName: "Cymraeg" },
  { tag: "da", englishName: "Danish", nativeName: "dansk" },
  { tag: "dv", englishName: "Divehi" },
  { tag: "eo", englishName: "Esperanto", nativeName: "Esperanto" },
  { tag: "et", englishName: "Estonian", nativeName: "eesti" },
  { tag: "fo", englishName: "Faroese", nativeName: "føroyskt" },
  { tag: "fj", englishName: "Fijian" },
  { tag: "fi", englishName: "Finnish", nativeName: "suomi" },
  { tag: "fy", englishName: "Western Frisian", nativeName: "Frysk" },
  { tag: "gd", englishName: "Scottish Gaelic", nativeName: "Gàidhlig" },
  { tag: "ga", englishName: "Irish", nativeName: "Gaeilge" },
  { tag: "gl", englishName: "Galician", nativeName: "galego" },
  { tag: "gn", englishName: "Guarani" },
  { tag: "ht", englishName: "Haitian Creole" },
  { tag: "haw", englishName: "Hawaiian", nativeName: "ʻŌlelo Hawaiʻi" },
  { tag: "hy", englishName: "Armenian", nativeName: "հայերեն" },
  { tag: "io", englishName: "Ido" },
  { tag: "ia", englishName: "Interlingua", nativeName: "interlingua" },
  { tag: "is", englishName: "Icelandic", nativeName: "íslenska" },
  { tag: "ka", englishName: "Georgian", nativeName: "ქართული" },
  { tag: "km", englishName: "Khmer", nativeName: "ខ្មែរ" },
  { tag: "ky", englishName: "Kyrgyz", nativeName: "кыргызча" },
  { tag: "lo", englishName: "Lao", nativeName: "ລາວ" },
  { tag: "la", englishName: "Latin" },
  { tag: "lv", englishName: "Latvian", nativeName: "latviešu" },
  { tag: "lt", englishName: "Lithuanian", nativeName: "lietuvių" },
  { tag: "lb", englishName: "Luxembourgish", nativeName: "Lëtzebuergesch" },
  { tag: "mk", englishName: "Macedonian", nativeName: "македонски" },
  { tag: "mt", englishName: "Maltese", nativeName: "Malti" },
  { tag: "mn", englishName: "Mongolian", nativeName: "монгол" },
  { tag: "mi", englishName: "Māori", nativeName: "Māori" },
  { tag: "nso", englishName: "Northern Sotho", nativeName: "Sesotho sa Leboa" },
  { tag: "oc", englishName: "Occitan", nativeName: "occitan" },
  { tag: "or", englishName: "Odia", nativeName: "ଓଡ଼ିଆ" },
  { tag: "om", englishName: "Oromo", nativeName: "Oromoo" },
  { tag: "fa-AF", englishName: "Dari", nativeName: "دری" },
  { tag: "sa", englishName: "Sanskrit", nativeName: "संस्कृत भाषा" },
  { tag: "sk", englishName: "Slovak", nativeName: "slovenčina" },
  { tag: "sl", englishName: "Slovenian", nativeName: "slovenščina" },
  { tag: "sm", englishName: "Samoan" },
  { tag: "sn", englishName: "Shona", nativeName: "chiShona" },
  { tag: "sd", englishName: "Sindhi", nativeName: "سنڌي" },
  { tag: "st", englishName: "Southern Sotho", nativeName: "Sesotho" },
  { tag: "ty", englishName: "Tahitian" },
  { tag: "tt", englishName: "Tatar", nativeName: "татар" },
  { tag: "tg", englishName: "Tajik", nativeName: "тоҷикӣ" },
  { tag: "ti", englishName: "Tigrinya", nativeName: "ትግርኛ" },
  { tag: "to", englishName: "Tongan", nativeName: "lea fakatonga" },
  { tag: "tn", englishName: "Tswana", nativeName: "Setswana" },
  { tag: "tk", englishName: "Turkmen", nativeName: "türkmen dili" },
  { tag: "ug", englishName: "Uyghur", nativeName: "ئۇيغۇرچە" },
  { tag: "vo", englishName: "Volapük" },
  { tag: "wo", englishName: "Wolof", nativeName: "Wolof" },
  { tag: "xh", englishName: "Xhosa", nativeName: "IsiXhosa" },
  { tag: "yi", englishName: "Yiddish", nativeName: "ייִדיש" },
  { tag: "ak", englishName: "Akan", nativeName: "Akan" },
  { tag: "bm", englishName: "Bambara", nativeName: "bamanakan" },
  { tag: "bi", englishName: "Bislama" },
  { tag: "bo", englishName: "Tibetan", nativeName: "བོད་སྐད་" },
  { tag: "ce", englishName: "Chechen", nativeName: "нохчийн" },
  { tag: "cv", englishName: "Chuvash", nativeName: "чӑваш чӗлхи" },
  { tag: "dz", englishName: "Dzongkha", nativeName: "རྫོང་ཁ" },
  { tag: "ee", englishName: "Ewe", nativeName: "eʋegbe" },
  { tag: "kab", englishName: "Kabyle", nativeName: "Taqbaylit" },
  { tag: "lg", englishName: "Ganda", nativeName: "Luganda" },
  { tag: "os", englishName: "Ossetic", nativeName: "ирон" },
  { tag: "ss", englishName: "Swati" },
  { tag: "ve", englishName: "Venda" },
  { tag: "war", englishName: "Waray" },
  { tag: "nd", englishName: "North Ndebele", nativeName: "isiNdebele" },
  { tag: "nr", englishName: "South Ndebele" },
  { tag: "pam", englishName: "Pampanga" },
  { tag: "hil", englishName: "Hiligaynon" },
  { tag: "bik", englishName: "Bikol" },
  { tag: "min", englishName: "Minangkabau" },
  { tag: "ace", englishName: "Acehnese" },
  { tag: "bug", englishName: "Buginese" },
  { tag: "ban", englishName: "Balinese" },
  { tag: "bjn", englishName: "Banjar" },
  { tag: "mak", englishName: "Makasar" },
  { tag: "sas", englishName: "Sasak" },
  { tag: "tet", englishName: "Tetum" },
  { tag: "ch", englishName: "Chamorro" },
  { tag: "niu", englishName: "Niuean" },
  { tag: "tvl", englishName: "Tuvalu" },
  { tag: "gil", englishName: "Gilbertese" },
  { tag: "mh", englishName: "Marshallese" },
  { tag: "pau", englishName: "Palauan" },
  { tag: "wls", englishName: "Wallisian" },
  { tag: "rar", englishName: "Rarotongan" },
  { tag: "hif", englishName: "Fiji Hindi" },
];
